-- Listing #001: the one genuine listing the MVP launches with.
-- Facts taken directly from the brief. Anything not supplied is left as
-- NULL or an explicit "[TO VERIFY]" placeholder rather than invented.
insert into listings (
  slug,
  listing_type,
  status,
  manufacturer,
  model,
  year,
  registration,
  location,
  airport_name,
  airport_code,
  price,
  share_fraction,
  monthly_cost,
  hourly_cost,
  engine_summary,
  engine_rebuilt_date,
  engine_hours_since_rebuild,
  insured_hull_value,
  description,
  group_facts,
  insurance_info,
  images,
  published_at
) values (
  'piper-pa28-cherokee-180-share',
  'share',
  'active',
  'Piper',
  'PA-28 Cherokee 180',
  1967,
  '[TO VERIFY]',
  'Blackbushe Airport',
  'Blackbushe Airport',
  'EGLK',
  8000,
  '1/8',
  110,
  105,
  'Factory-rebuilt engine fitted in January 2025 by Nicholson McLaren.',
  'January 2025',
  70,
  70000,
  E'A rare opportunity to acquire a 1/8 share in a Piper PA-28 Cherokee 180 based at Blackbushe Airport.\n\nThe aircraft is operated by a well-established eight-member syndicate and offers great availability, straightforward online booking and a very well-maintained aircraft.\n\nThe share is being sold because the current owner has acquired a share in another aircraft.\n\nShares in established aircraft at Blackbushe do not necessarily become available frequently, making this an attractive opportunity for someone looking to move into aircraft ownership without the cost of sole ownership.',
  '[
    "Established eight-member syndicate",
    "Great aircraft availability",
    "Straightforward online booking system",
    "Very well-maintained aircraft",
    "New-member checkout",
    "Flying abroad is permitted subject to the pilot''s licence, qualifications and applicable requirements"
  ]'::jsonb,
  'The current insurance requirement is 100 hours total flying experience. A new member below the 100-hour level may potentially still join but would be responsible for the additional insurance premium and likely increased compulsory excess applicable until reaching the required experience level.',
  '[
    {"src": "/images/listings/001/01-front-three-quarter.svg", "alt": "Front three-quarter exterior", "order": 1},
    {"src": "/images/listings/001/02-side-profile.svg", "alt": "Side profile", "order": 2},
    {"src": "/images/listings/001/03-rear-three-quarter.svg", "alt": "Rear three-quarter", "order": 3},
    {"src": "/images/listings/001/04-cockpit-wide.svg", "alt": "Cockpit wide shot", "order": 4},
    {"src": "/images/listings/001/05-instrument-panel.svg", "alt": "Instrument panel", "order": 5},
    {"src": "/images/listings/001/06-front-seats.svg", "alt": "Front seats and interior", "order": 6},
    {"src": "/images/listings/001/07-rear-seating.svg", "alt": "Rear seating", "order": 7},
    {"src": "/images/listings/001/08-engine-cowling-open.svg", "alt": "Engine and cowling open", "order": 8},
    {"src": "/images/listings/001/09-propeller-nose.svg", "alt": "Propeller and nose", "order": 9},
    {"src": "/images/listings/001/10-undercarriage.svg", "alt": "Undercarriage", "order": 10},
    {"src": "/images/listings/001/11-blackbushe-apron.svg", "alt": "Aircraft on the Blackbushe apron", "order": 11},
    {"src": "/images/listings/001/12-airfield-context.svg", "alt": "Aircraft and airfield context", "order": 12}
  ]'::jsonb,
  now()
);
